apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-protected
  namespace: my-namespace
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`myapp.lab`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      middlewares:
        - name: auth-forward
      services:
        - name: my-app
          port: 80
