apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dopdocai-route-protected
  namespace: dopdocai
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dopdocai.lab`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      middlewares:
        - name: auth-forward
      services:
        - name: dopdocai
          port: 80
