apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dopdocai-public
  namespace: dopdocai
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.dopdocai.lab`) && (PathPrefix(`/auth`) || PathPrefix(`/refresh`) || PathPrefix(`/logout`) || PathPrefix(`/register`))
      kind: Rule
      priority: 100
      services:
        - name: dopdoc-auth-service
          port: 9200