apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dopdocai-route
  namespace: dopdocai
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dopdocai.lab`) && (PathPrefix(`/auth`) || PathPrefix(`/refresh`) || PathPrefix(`/logout`) || PathPrefix(`/register`))
      kind: Rule
      priority: 100
      services:
        - name: my-app
          port: 80