apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend.yaml
  - ./ingressroute-protected.yaml
  - ./ingressroute-public.yaml
  - ./middleware.yaml
  - ./ns.yaml
  - ./postgres.yaml